=== Mr-P-o-s-T/Object-oriented-programming.Java/LAB.2/XSD/input.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="LAB.2"
           xmlns="LAB.2"
           elementFormDefault="qualified">

    <xs:element name="guns">
        <xs:complexType>
            <xs:sequence maxOccurs="unbounded">
                <xs:element name="gun" type="gun" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="gun">
        <xs:sequence>
            <xs:element name="model" type="xs:string" />
            <xs:element name="handy" type="handyType" />
            <xs:element name="origin" type="xs:string" />
            <xs:element name="TTC" type="TTC" />
            <xs:element name="materials" type="materialsType" />
        </xs:sequence>
        <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
    </xs:complexType>
    
    <xs:complexType name="handyType">
        <xs:attribute name="num" type="handyNumber" use="required" />
    </xs:complexType>

    <xs:simpleType name="handyNumber">
        <xs:restriction base="xs:integer">
            <xs:enumeration value="1" />
            <xs:enumeration value="2" />
        </xs:restriction>
    </xs:simpleType>
    
    <xs:complexType name="TTC">
        <xs:sequence>
            <xs:element name="range" type="rangeType" />
            <xs:element name="sightingRange" type="sightingRangeType" />
            <xs:element name="attachments" type="attachmentsType" />
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="rangeType">
        <xs:attribute name="type" type="rangeValue" use="required" />
    </xs:complexType>
    
    <xs:simpleType name="rangeValue">
        <xs:restriction base="xs:string">
            <xs:enumeration value="near" />
            <xs:enumeration value="medium" />
            <xs:enumeration value="far" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="sightingRangeType">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="0" />
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="attachmentsType">
        <xs:sequence>
            <xs:element name="clip" type="xs:string" fixed="" minOccurs="0" />
            <xs:element name="optics" type="xs:string" fixed="" minOccurs="0" />
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="materialsType">
        <xs:sequence maxOccurs="unbounded">
            <xs:element name="material" type="xs:string" />
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== Mr-P-o-s-T/Object-oriented-programming.Java/LAB.2/XML/input.xml
<?xml version="1.0" encoding="UTF-8" ?>
<guns xmlns="LAB.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="LAB.2 ../XSD/input.xsd">
    <gun id="3">
        <model>Model 1 Pistol</model>
        <handy num="1" />
        <origin>Country 1</origin>
        <TTC>
            <range type="near" />
            <sightingRange>30</sightingRange>
            <attachments>
                <clip />
            </attachments>
        </TTC>
        <materials>
            <material>Steel</material>
            <material>Wood</material>
        </materials>
    </gun>

    <gun id="2">
        <model>Model 2 SMG</model>
        <handy num="2"/>
        <origin>Country 1</origin>
        <TTC>
            <range type="near"/>
            <sightingRange>150</sightingRange>
            <attachments>

            </attachments>
        </TTC>
        <materials>
            <material>Steel</material>
        </materials>
    </gun>

    <gun id="4">
        <model>Model 3 Automatic Rifle</model>
        <handy num="2"/>
        <origin>Country 1</origin>
        <TTC>
            <range type="medium"/>
            <sightingRange>450</sightingRange>
            <attachments>

            </attachments>
        </TTC>
        <materials>
            <material>Steel</material>
            <material>Wood</material>
        </materials>
    </gun>

    <gun id="1">
        <model>Model 4 Rifle</model>
        <handy num="2"/>
        <origin>Country 1</origin>
        <TTC>
            <range type="far"/>
            <sightingRange>800</sightingRange>
            <attachments>
                <clip />
                <optics />
            </attachments>
        </TTC>
        <materials>
            <material>Wood</material>
            <material>Steel</material>
        </materials>
    </gun>
</guns>
